version: "3"
services:
  jenkins:
    build: ./cd_jenkins
    image: cd_jenkins:latest
    ports:
      - "8080:8080"
      - "5000:5000"
    links:
      - nexus
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ramlfiles:/raml-files
      - robottests:/robot-tests
  nexus:
    image: sonatype/nexus3:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nexus-data:/nexus-data
  test_fixture:
    build: ./test_fixture
    image: test_fixture:latest
    volumes:
          - ./chef-repo:/chef-repo
    ports:
      - "8888:8888"
      - "22:22"
  abao:
    build: ./raml-files
    image: abao:latest
volumes:
  ramlfiles:
    driver_opts:
      type: none
      device: $PWD/raml-files
      o: bind
  robottests:
    driver_opts:
          type: none
          device: $PWD/robot-tests
          o: bind
